---
title: "data_visualization"
format: html
editor: visual
---

## Import Data

```{r}
data <- read.csv("ML_wind_data.csv")
data

```


```{r}
library(ggplot2)


ggplot(data, aes(x = scaled_aggregate)) +
  geom_histogram()+ labs(x = "Scaled Aggregate", y = "Count", fill = "Year", title = "Histogram of the Distributed Aggregate Statistics", caption = "Data from NOAA storm events database", subtitle = "The majority of events had no devastation followed by minimal devastation")
```


```{r}
ggplot(data, aes(x = scaled_aggregate, fill = factor(YEAR))) +
  geom_histogram(binwidth = (max(data$scaled_aggregate) - min(data$scaled_aggregate)) / 15, 
                 alpha = 0.6, position = "dodge", boundary = 0) +  
  scale_fill_manual(values = c("2018" = "blue", "2008" = "red", "2013" = "green")) +    labs(x = "Scaled Aggregate", y = "Count", fill = "Year", title = "Histogram of the Aggregate Statistics grouped by year", caption = "Data from NOAA storm events database", subtitle  = "Distirbution by years are pretty similar but 2008 has the most devastation") 

```

```{r}
ggplot(data, aes(x = scaled_aggregate, fill = factor(MONTH_NAME))) +
  geom_histogram(binwidth = (max(data$scaled_aggregate) - min(data$scaled_aggregate)) / 15, 
                 alpha = 0.6, position = "dodge", boundary = 0)   + labs(x = "Scaled Aggregate", y = "Count", fill = "Year", title = "Histogram of the Aggregate Statistics grouped by month", caption = "Data from NOAA storm events database", subtitle = "Events during summer months appear to cause the most devastation") 
```
```{r}
ggplot(data, aes(x = scaled_aggregate, fill = EVENT_TYPE)) +
  geom_histogram(binwidth = (max(data$scaled_aggregate) - min(data$scaled_aggregate)) / 15, 
                 alpha = 0.6, position = "dodge", boundary = 0)   + labs(x = "Scaled Aggregate", y = "Count", fill = "Year", title = "Histogram of the Aggregate Statistics grouped by event type", caption = "Data from NOAA storm events database", subtitle = "Majority of the data is from thunderstorm wind events.") 
```

