project:
  type: website

website:
  title: "Team Windows Website"
  navbar:
    left:
      - href: index.qmd
        text: Background
      - href: Data_Visualization.qmd
        text: Data Visualization
      - href: Wind_Categorization.qmd
        text: Wind Devastation Categorization
      - href: Machine_Learning_Model.qmd
        text: Machine Learning Model

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



